remove invalid input kwarg
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/cog/command/openapi_schema.py", line 24, in <module>
    app = create_app(predictor)
  File "/usr/local/lib/python3.8/site-packages/cog/server/http.py", line 34, in create_app
    InputType = get_input_type(predictor)
  File "/usr/local/lib/python3.8/site-packages/cog/predictor.py", line 126, in get_input_type
    return create_model("Input", **create_model_kwargs)
  File "pydantic/main.py", line 972, in pydantic.main.create_model
  File "pydantic/main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 486, in pydantic.fields.ModelField.infer
  File "pydantic/schema.py", line 1012, in pydantic.schema.get_annotation_from_field_info
ValueError: On field "source_image" the following field constraints are set but not enforced: ge.
For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints

ⅹ Failed to get type signature: exit status 1